[phases.setup]
nixPkgs = ["php83", "php83Extensions.gd", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.zip", "php83Extensions.xml", "composer"]

[start]
cmd = "apache2-foreground"